version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: dklyle/hello-node:v2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
